Improvement to examples and various fixes
wolfSSL/wolfKeyMgr pull request #3
Opened 2021-10-26 23:38 UTC by dgarske

* Add argument support to HTTP server.
* Improve error when key manager connection fails.
* Fix `ets_test` help messages for fingerprint and context string.
* Fix "ETSI" references to be "ETS" (Enterprise Transport Security)... not ETSI org.
* Fix HTTPS example server to send shutdown.
* Fixes to support `HAVE_PUBLIC_FFDHE` not defined.
* Add support for x448.

2021-11-05 18:35 UTC, anhu requested changes

2021-11-05 18:35 UTC, anhu commented on examples/https/server.c
> +                printf("\nFailure connecting to key manager\n");
Since this is an error, I think it should go to stderr. (here and all other error output).

2021-11-05 18:35 UTC, anhu commented on src/mod_tls.c
> +    #if 0
Maybe add a comment saying that if you enable this code, ensure HAVE_CURVE_X448 is defined or add guard inside the `#if 0`

2021-11-05 18:40 UTC, anhu commented
```
ets_test.c:60:    /* TODO: Add error case */
```

Address this comment. Maybe just remove it ?

2021-11-05 18:41 UTC, anhu commented
ets_test.h copyright notice seems strange ....it didn't exist in 2006 .  In fact, I don't think that file is even required. all it does is declare `ets_test()` .  Maybe remove the file?

2021-11-05 18:43 UTC, anhu commented
above comment seems to apply to all the .h files in the examples.

2021-11-05 18:47 UTC, anhu commented
```
examples/https/README.md:5:## TlS Server
wolfssl/wolfcrypt/src/port/Renesas/README.md:64:*Perform full TlS-linked capability*
```
Capitalize the 'l' in TLS

2021-11-05 18:48 UTC, anhu commented
Makefile.am needs a copyright notice.

2021-11-05 18:55 UTC, anhu commented
remove scripts directory.  There is nothing there.

2021-11-05 18:56 UTC, anhu commented
gen-cert.sh needs a copyright notice.

2021-11-08 14:12 UTC, anhu commented
Missed one: 

`wolfssl/wolfcrypt/src/port/Renesas/README.md:64:*Perform full TlS-linked capability*`

2021-11-08 16:34 UTC, dgarske commented
> Missed one:
> 
> `wolfssl/wolfcrypt/src/port/Renesas/README.md:64:*Perform full TlS-linked capability*`

This is not in this repo but should be fixed in wolfSSL

2021-11-08 16:44 UTC, anhu commented
ah...I see now.  I'll get that fixed.

2021-11-08 17:37 UTC, dgarske commented
Note: The x448 support requires: https://github.com/wolfSSL/wolfssl/pull/4522

2021-11-08 19:15 UTC, anhu commented
got this at end of output of `./examples/middlebox/decrypt`
```
SSL App Data(22:132):HTTP/1.1 200 OK
Content-Type: text/html
Connection: keep-alive
Content-Length: 44

<html><body><h1>It works!</h1></body></html>
Found ETS static ephemeral key (121 bytes)
ssl_Decode ret = -2, Session in Fatal Error State
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found
ssl_Decode ret = -1, Session Not Found

```

2021-11-08 19:28 UTC, dgarske commented
> got this at end of output of `./examples/middlebox/decrypt`
> 
> ```
> SSL App Data(22:132):HTTP/1.1 200 OK
> Content-Type: text/html
> Connection: keep-alive
> Content-Length: 44
> 
> <html><body><h1>It works!</h1></body></html>
> Found ETS static ephemeral key (121 bytes)
> ssl_Decode ret = -2, Session in Fatal Error State
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ssl_Decode ret = -1, Session Not Found
> ```

That is okay... this sniffer is doing a capture of all localhost traffic on 443, so there may be other data which the ephemeral key is not known. You can see the expected `It works!`. You are welcome to add some debugging logging using DEBUG_SNIFFER and adding a log file parameter to wolfKeyMgr_SetLogFile.

2021-11-08 19:50 UTC, anhu commented
> That is okay... 

OK, I'm with this then.  I just wasn't sure if you were aware it was happening.

2021-11-08 19:51 UTC, anhu commented
Look good to me...

2021-11-08 19:55 UTC, anhu approved these changes

2021-11-08 19:57 UTC, merged